// frontend/src/pages/Signin.jsx
import React, { useEffect, useContext } from "react"
import AuthContext from "../contexts/authContext"
import isLoggedIn from "../middlewares/isLoggedIn"
import { useNavigate, Link } from "react-router-dom"
import { useForm } from "react-hook-form"
import { yupResolver } from "@hookform/resolvers/yup"
import * as yup from "yup"
import Swal from "sweetalert2/dist/sweetalert2.all.min.js"
import { useMutation } from "@apollo/client"
import { LOGIN_MUTATION } from "../graphql/loginMutation"
import Cookies from "js-cookie"

const schema = yup
  .object({
    email: yup.string().max(100).email().required(),
    password: yup.string().min(8).max(30).required(),
  })
  .required()

function Signin(props) {
  // Middleware
  const me = useContext(AuthContext)
  const navigate = useNavigate()
  useEffect(() => {
    isLoggedIn(props.meta, me, navigate)
  }, [])

  const [login] = useMutation(LOGIN_MUTATION)

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
  })
  const onSubmit = async (data) => {
    let { email, password } = data
    try {
      const response = await login({ variables: { email, password } })
      if (response.data.login.status === "success") {
        Cookies.set("token", response.data.login.token)
        await props.refetch()
        navigate("/")
      } else {
        Swal.fire({
          title: "ไม่สำเร็จ",
          text: response.data.login.message,
          icon: "error",
        })
      }
    } catch (errors) {
      console.log(errors)
      Swal.fire({
        title: "ไม่สำเร็จ",
        text: errors.message,
        icon: "error",
      })
    }
  }
  return (
    <>
      <div className="h2">เข้าสู่ระบบ</div>
      <hr />
      <br />
      <br />
      <div className="col-lg-6 col-md-8 col-sm-12 m-auto">
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className="mb-3">
            <label className="form-label">อีเมล</label>
            <input
              type="text"
              className="form-control"
              placeholder="อีเมล"
              {...register("email")}
            />
            <div className="mt-1 text-danger">
              {errors.email && "โปรดกรอกอีเมลให้ถูกต้อง"}
            </div>
          </div>
          <div className="mb-3">
            <label className="form-label">รหัสผ่าน</label>
            <input
              type="password"
              className="form-control"
              placeholder="รหัสผ่าน"
              {...register("password")}
            />
            <div className="mt-1 text-danger">
              {errors.password &&
                "โปรดกรอกรหัสผ่านให้ถูกต้อง (8 - 30 ตัวอักษร)"}
            </div>
          </div>
          <div className="text-center mb-3">
            <button className="btn btn-primary" type="submit">
              เข้าสู่ระบบ
            </button>
            <div className="my-2">
              ไม่ได้เป็นสมาชิกใช่ไหม คลิกที่นี่เพื่อ{" "}
              <Link to="/signup">ลงทะเบียน</Link>
            </div>
          </div>
        </form>
      </div>
    </>
  )
}

export default Signin

// frontend/src/views/Signin.vue
<template>
  <div>
    <h2>เข้าสู่ระบบ</h2>
    <hr />
    <br />
    <div class="col-lg-6 m-auto">
      <form @submit.prevent="validateSignin()">
        <div class="mb-3">
          <label class="form-label" for="email">อีเมล</label>
          <input
            type="email"
            class="form-control"
            v-model="signin.email"
            placeholder="อีเมล"
            name="email"
            aria-describedby="email"
            required
          />
        </div>
        <div class="mb-3">
          <label class="form-label" for="password">รหัสผ่าน</label>
          <input
            type="password"
            class="form-control"
            v-model="signin.password"
            placeholder="รหัสผ่าน"
            name="password"
            required
          />
        </div>
        <div class="mb-3 text-center">
          <button type="submit" class="btn btn-primary">เข้าสู่ระบบ</button>
        </div>
        <div class="mb-3 text-center">
          ไม่ได้เป็นสมาชิกใช่ไหม คลิกที่นี่เพื่อ
          <router-link to="/signup">ลงทะเบียน</router-link>
        </div>
      </form>
    </div>
  </div>
</template>
<script>
import Swal from "sweetalert2";
import axios from "axios";
import { HTTP, SERVER_IP, PORT } from "../assets/js/SERVER_IP";

export default {
  data() {
    return {
      signin: {
        email: "",
        password: "",
      },
    };
  },
  methods: {
    SubmitSignin() {
      axios
        .post(`${HTTP}://${SERVER_IP}:${PORT}/signin`, this.signin)
        .then((res) => {
          const data = res.data;
          if (data.status) {
            localStorage.setItem("token", data.user.token);
            this.$router.push("/");
          } else {
            Swal.fire({
              title: "ไม่สำเร็จ",
              text: data.alert,
              icon: "error",
              timer: 3000,
              showConfirmButton: false,
            });
          }
        })
        .catch((err) => {
          console.log(err);
        });
    },
    validateSignin() {
      this.SubmitSignin();
    },
  },
  created() {
    if (localStorage.getItem("token") !== null) {
        this.$router.push('/')
    }
  },
};
</script>
